---

- name: Install apache2
  apt:
    name: apache2
    state: present

- name: Enable module apache2
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - rewrite
    - ssl
  when: mirror_ssl
  notify:
    - restart_apache2

- name: Config apache2
  template:
    src: repos.conf.j2
    dest: /etc/apache2/sites-available/repos.conf
  notify:
    - restart_apache2

- name: Remove default apache2 site.
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: restart apache2

- name: Enable site
  file:
    src: /etc/apache2/sites-available/repos.conf
    dest: /etc/apache2/sites-enabled/repos.conf
    state: link
  notify:
    - restart_apache2

- name: main | Cron job
  cron:
    name: "Update mirror hour {{ item.mirror_cron_hour }}"
    day: "{{ item.mirror_cron_day }}"
    hour: "{{ item.mirror_cron_hour }}"
    job: '{{ item.mirror_task }} --pre-hook "pkill rsync"'
  when: mirror_cron
  with_items: "{{ mirror_cron }}"
