---

- name: Add group
  group:
    name: "{{ mirror_group }}"
    state: present

- name: create users
  user:
    name: "{{ mirror_user.user }}"
    comment: "{{ mirror_user.name }}"
    uid: 1040
    group: "{{ mirror_user.group }}"

- name: main | Cron job
  cron:
    name: "Update mirror hour {{ item.mirror_cron_hour }}"
    user: "{{ mirror_user.user }}"
    day: "{{ item.mirror_cron_day }}"
    hour: "{{ item.mirror_cron_hour }}"
    job: '{{ item.mirror_task }} --pre-hook "pkill rsync"'
  when: mirror_cron
  with_items: "{{ mirror_cron }}"
