---

- name: Create directory mirror
  file:
    path: "{{ mirror_scripts_path }}/{{ item }}"
    state: directory
  with_items:
    - debian
    - debian/debian
    - debian/debian/etc
    - debian/debian/bin
    - debian/debian-cd
    - debian/debian-cd/etc
    - debian/debian-cd/bin
    - ubuntu

- name: Template | repository Debian
  template:
    src: ftpsync.conf.j2
    dest: "{{ mirror_scripts_path }}/debian/debian/etc/ftpsync.conf"
    owner: "{{ mirror_user.user }}"
    mode: 0766

- name: Template | repository Debian-cd
  template:
    src: ftpsync-cd.conf.j2
    dest: "{{ mirror_scripts_path }}/debian/debian-cd/etc/ftpsync.conf"
    owner: "{{ mirror_user.user }}"
    mode: 0766

- name: Copy ftpsync
  copy:
    src: "files/ftpsync/bin/ftpsync"
    dest: "{{ item }}"
    owner: "{{ mirror_user.user }}"
    group: "{{ mirror_user.group }}"
    mode: 0766
  with_items:
    - "{{ mirror_scripts_path }}/debian/debian/bin/ftpsync"
    - "{{ mirror_scripts_path }}/debian/debian-cd/bin/ftpsync"

- name: Copy notify telegram
  template:
    src: 'notify_telegram.sh.j2'
    dest: "{{ mirror_scripts_path }}/notify_telegram.sh"
    owner: "{{ mirror_user.user }}"
    mode: 0766

- name: Page init
  template:
    src: index.html.j2
    dest: /var/www/html/mirror/index.html
    owner: "{{ mirror_user.user }}"
    mode: 0644

- name: Copy image
  copy:
    src: "{{ mirror_image_path }}/{{ mirror_image }}"
    dest: /var/www/html/mirror/{{ mirror_image }}
    owner: "{{ mirror_user.user }}"
    group: "{{ mirror_user.group }}"
    mode: 0644
