---

- name: Create directory scripts
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mirror_user.user }}"
    group: "{{ mirror_user.group }}"
  with_items:
  - "{{mirror_debian_scripts_root_path}}"
  - "{{mirror_debian_scripts_path}}"
  - "{{mirror_debian_scripts_path}}/etc"
  - "{{mirror_debian_scripts_path}}/bin"
  - "{{mirror_debian_cd_scripts_path}}"
  - "{{mirror_debian_cd_scripts_path}}/etc"
  - "{{mirror_debian_cd_scripts_path}}/bin"
  - "{{mirror_ubuntu_scripts_path}}"  

- name: Create directory mirror
  file:
    path: "{{ mirror_base_path }}/{{ item }}"
    state: directory
    owner: "{{ mirror_user.user }}"
    group: "{{ mirror_user.group }}"
  with_items:
    - debian
    - ubuntu

- name: Create symbolic link
  file:
    src: "{{ mirror_base_path }}"
    dest: "{{ mirror_apache_path }}"
    state: link

- name: Template | repository Debian
  template:
    src: ftpsync.conf.j2
    dest: "{{ mirror_debian_scripts_path }}/etc/ftpsync.conf"
    owner: "{{ mirror_user.user }}"
    mode: 0766

- name: Template | repository Debian-cd
  template:
    src: ftpsync-cd.conf.j2
    dest: "{{ mirror_debian_cd_scripts_path }}/etc/ftpsync.conf"
    owner: "{{ mirror_user.user }}"
    mode: 0766

- name: Copy ftpsync
  copy:
    src: "files/ftpsync/bin/ftpsync"
    dest: "{{ item }}"
    owner: "{{ mirror_user.user }}"
    group: "{{ mirror_user.group }}"
    mode: 0766
  with_items:
    - "{{ mirror_debian_scripts_path }}/bin/ftpsync"
    - "{{ mirror_debian_cd_scripts_path }}/bin/ftpsync"

- name: Copy notify telegram
  template:
    src: 'notify_telegram.sh.j2'
    dest: "{{ mirror_scripts_path }}/notify_telegram.sh"
    owner: "{{ mirror_user.user }}"
    mode: 0766
  when: mirror_telegram_token != ""

- name: Copy script ubuntu
  template:
    src: '{{ item }}.j2'
    dest: "{{ mirror_ubuntu_scripts_path }}/{{ item }}"
    owner: "{{ mirror_user.user }}"
    mode: 0766
  with_items:
    - "ubuntu.sh"
    - "ubuntu-release.sh"

- name: Page init
  template:
    src: index.html.j2
    dest: "{{mirror_apache_path}}/{{ mirror_page_init }}"
    owner: "{{ mirror_user.user }}"
    mode: 0644

- name: Copy image
  copy:
    src: "{{ mirror_image_path }}/{{ mirror_image }}"
    dest: "{{ mirror_apache_path }}/{{ mirror_image }}"
    owner: "{{ mirror_user.user }}"
    group: "{{ mirror_user.group }}"
    mode: 0644
